name: ieps-visualization

services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgresql-wier-viz
    environment:
      POSTGRES_PASSWORD: SecretPassword
      POSTGRES_USER: user
      POSTGRES_DB: crawldb
    ports:
      - "5433:5432"
    volumes:
      - ../.docker/pgdata-viz:/var/lib/postgresql/data
      - ../pa1/db/crawldb.sql:/docker-entrypoint-initdb.d/01-crawldb.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d crawldb"]
      interval: 5s
      timeout: 3s
      retries: 20
