#!/usr/bin/env python3
"""
PA2 retrieval demo for course markers (Phase 5).

Purpose:
- Accept a natural-language query.
- Embed the query with the same embedding model used for segment indexing.
- Search `crawldb.page_segment` with pgvector similarity operators.
- Optionally rerank candidates with a cross-encoder.
- Provide a built-in qualitative evaluation mode (3 good + 3 weak queries).

System role:
- Depends on embeddings generated by `embed_page_segments.py`.
- Reads from `crawldb.page_segment` and joins source URL from `crawldb.page`.

Created: 2026-05-06
Major revisions:
- 2026-05-06: Implemented retrieval CLI, metric experiments, reranking, and eval mode.
- 2026-05-26: Delegated retrieval logic to retrieval.py for PA3 reuse.
"""

from __future__ import annotations

import argparse
import logging
import os
import shutil
import sys
import textwrap
from typing import Sequence

from embedding_common import parse_embedding_backend
from retrieval import (
    METRIC_TO_OPERATOR,
    RetrievalConfig,
    RetrievalHit,
    connect,
    embed_query,
    rerank_hits,
    retrieve_hits,
)

EVAL_QUERY_SETS = {
    "good": [
        "How do I evaluate mIoU or accuracy on the validation set?",
        "What are some of the repositories for food image classification?",
        "How do I run Segment Anything (SAM) inference or download SAM checkpoints from this repository?",
    ],
    "weak": [
        "What is the best segmentation model for medical biology images in 2026?",
        "Which segmentation model should my hospital buy for regulatory approval in the EU?",
        "What exact mIoU did this repo achieve on Cityscapes compared to Mask2Former last month?",
    ],
}

ANSI_RESET = "\033[0m"
ANSI_BOLD = "\033[1m"
ANSI_CYAN = "\033[36m"
ANSI_MAGENTA = "\033[35m"
ANSI_YELLOW = "\033[33m"


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Build CLI argument parser and return parsed namespace."""
    parser = argparse.ArgumentParser(
        description="PA2 demo: semantic retrieval over crawldb.page_segment embeddings."
    )
    parser.add_argument(
        "--query",
        type=str,
        default=None,
        help="Natural-language query to retrieve against segment embeddings.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Number of results to display (default: 5).",
    )
    parser.add_argument(
        "--strategy",
        type=str,
        default="heading_structure_v4",
        help="Optional segment strategy filter (default: heading_structure_v4).",
    )
    parser.add_argument(
        "--metric",
        choices=tuple(METRIC_TO_OPERATOR.keys()),
        default="cosine",
        help="Similarity metric/operator to use (default: cosine).",
    )
    parser.add_argument(
        "--embedding",
        choices=("minilm", "labse"),
        default="minilm",
        help="First-stage bi-encoder and pgvector column (minilm→embedding, labse→embedding_labse).",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help=(
            "SentenceTransformer model id for the query vector. "
            "Default follows --embedding; if set, must exactly match the registry id for that backend."
        ),
    )
    parser.add_argument(
        "--rerank",
        action="store_true",
        help="Enable cross-encoder reranking over retrieved candidates.",
    )
    parser.add_argument(
        "--rerank-model",
        type=str,
        default="cross-encoder/ms-marco-MiniLM-L-6-v2",
        help="Cross-encoder model name used when --rerank is enabled.",
    )
    parser.add_argument(
        "--candidate-k",
        type=int,
        default=20,
        help="Candidate pool size before reranking (default: 20).",
    )
    parser.add_argument(
        "--database-url",
        type=str,
        default=os.environ.get("DATABASE_URL"),
        help="PostgreSQL connection URI. If omitted, falls back to PG* environment variables.",
    )
    parser.add_argument(
        "--run-eval",
        action="store_true",
        help="Run built-in qualitative query set (3 good + 3 weak queries).",
    )
    parser.add_argument(
        "--show-chars",
        type=int,
        default=260,
        help="Number of text characters to show per hit preview (default: 260).",
    )
    parser.add_argument(
        "--no-normalize",
        action="store_true",
        help="Disable L2 normalization when embedding the query.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable DEBUG logging.",
    )
    return parser.parse_args(argv)


def _format_preview(text: str, *, max_chars: int) -> str:
    """Render full segment text with line wrapping (no truncation)."""
    stripped = text.strip()
    if not stripped:
        return ""

    terminal_columns = shutil.get_terminal_size(fallback=(120, 24)).columns
    max_safe_width = max(40, terminal_columns - 8)
    wrap_width = min(max(40, max_chars), max_safe_width, 100)
    wrapped_lines: list[str] = []
    for raw_line in stripped.splitlines():
        if not raw_line.strip():
            wrapped_lines.append("")
            continue
        wrapped = textwrap.wrap(
            raw_line,
            width=wrap_width,
            replace_whitespace=False,
            drop_whitespace=False,
            break_long_words=False,
            break_on_hyphens=False,
        )
        wrapped_lines.extend(wrapped if wrapped else [""])
    return "\n".join(wrapped_lines)


def _supports_color() -> bool:
    """Return True when stdout likely supports ANSI colors."""
    if os.environ.get("NO_COLOR"):
        return False
    return sys.stdout.isatty()


def _style(text: str, *, role: str, use_color: bool) -> str:
    """Apply role-based ANSI styling for readability when supported."""
    if not use_color:
        return text
    if role == "header":
        return f"{ANSI_BOLD}{ANSI_MAGENTA}{text}{ANSI_RESET}"
    if role == "label":
        return f"{ANSI_BOLD}{ANSI_CYAN}{text}{ANSI_RESET}"
    if role == "section":
        return f"{ANSI_BOLD}{ANSI_YELLOW}{text}{ANSI_RESET}"
    if role == "meta_key":
        return f"{ANSI_BOLD}{text}{ANSI_RESET}"
    return text


def _format_meta_row(key: str, value: str, *, use_color: bool) -> str:
    """Format one metadata row with bold key and aligned value."""
    key_text = _style(f"{key:<12}", role="meta_key", use_color=use_color)
    return f"| {key_text} : {value}"


def _print_segment_text_block(preview: str) -> None:
    """Print multiline segment body inside card body with indentation."""
    if not preview:
        print("|   [EMPTY SEGMENT]")
        return
    for line in preview.splitlines():
        print(f"|   {line}")


def _print_hits(
    hits: Sequence[RetrievalHit],
    *,
    metric: str,
    show_chars: int,
    reranked: bool,
    use_color: bool,
) -> None:
    """Print retrieval results in card-style blocks."""
    if not hits:
        print(f"{_style('NO HITS', role='section', use_color=use_color)}")
        print("  No segments matched this query.")
        return

    border = "+" + "-" * 110 + "+"
    score_label = "rerank_score" if reranked else "distance"
    for rank, hit in enumerate(hits, start=1):
        preview = _format_preview(hit.segment_text, max_chars=show_chars)
        score_value = hit.rerank_score if reranked else hit.distance
        print()
        print(border)
        print(f"| {_style(f'RESULT {rank}/{len(hits)}', role='section', use_color=use_color)}")
        print(border)
        print(
            _format_meta_row(
                "score",
                f"{score_label}={score_value:.6f}  metric={metric}",
                use_color=use_color,
            )
        )
        print(_format_meta_row("page_id", str(hit.page_id), use_color=use_color))
        print(_format_meta_row("segment_id", str(hit.segment_id), use_color=use_color))
        print(_format_meta_row("chunk_index", str(hit.chunk_index), use_color=use_color))
        print(_format_meta_row("strategy", hit.strategy, use_color=use_color))
        print(
            _format_meta_row(
                "url",
                hit.source_url or "N/A",
                use_color=use_color,
            )
        )
        print(border)
        print(f"| {_style('SEGMENT TEXT', role='label', use_color=use_color)}")
        print(border)
        _print_segment_text_block(preview)
        print(border)


def _run_single_query(args: argparse.Namespace, query: str) -> int:
    """Execute one retrieval request and print results."""
    use_color = _supports_color()
    if args.metric != "cosine":
        logging.warning(
            "Metric '%s' has no matching ANN index in current migration (cosine HNSW only). "
            "Query is still valid, but may run slower.",
            args.metric,
        )

    query_vector = embed_query(
        query,
        model_name=args.model,
        normalize_embeddings=not args.no_normalize,
    )
    candidate_k = max(args.top_k, args.candidate_k if args.rerank else args.top_k)

    with connect(args.database_url) as conn:
        initial_hits = retrieve_hits(
            conn,
            query_vector=query_vector,
            top_k=candidate_k,
            strategy=args.strategy,
            metric=args.metric,
            embedding_pg_column=args.embedding_pg_column,
        )

    final_hits = initial_hits[: args.top_k]
    reranked = False
    if args.rerank:
        try:
            final_hits = rerank_hits(
                query,
                initial_hits,
                rerank_model=args.rerank_model,
                top_k=args.top_k,
            )
            reranked = True
        except Exception as exc:
            logging.warning("Reranking failed, falling back to base retrieval: %s", exc)

    print()
    print("#" * 100)
    print(f"{_style('QUERY', role='header', use_color=use_color)}: {query}")
    print(
        f"{_style('RUN CONFIG', role='header', use_color=use_color)}: "
        f"embedding={args.embedding} metric={args.metric} top_k={args.top_k} strategy={args.strategy or 'ALL'} "
        f"rerank={'on' if reranked else 'off'}"
    )
    print("#" * 100)
    _print_hits(
        final_hits,
        metric=args.metric,
        show_chars=args.show_chars,
        reranked=reranked,
        use_color=use_color,
    )
    print()
    return 0


def _run_eval(args: argparse.Namespace) -> int:
    """Run built-in qualitative query set required by the assignment."""
    print()
    print("#" * 100)
    print("Running qualitative evaluation set (3 good + 3 weak queries).")
    print("#" * 100)
    for bucket in ("good", "weak"):
        print()
        print("*" * 100)
        print(f"{bucket.upper()} QUERIES")
        print("*" * 100)
        for index, query in enumerate(EVAL_QUERY_SETS[bucket], start=1):
            print()
            print(f"[{bucket} query {index}]")
            _run_single_query(args, query)
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(message)s",
    )

    if args.top_k <= 0:
        raise ValueError("--top-k must be > 0")
    if args.candidate_k <= 0:
        raise ValueError("--candidate-k must be > 0")
    if args.show_chars <= 0:
        raise ValueError("--show-chars must be > 0")

    backend = parse_embedding_backend(args.embedding)
    if args.model is None:
        args.model = backend.model_id
    elif args.model != backend.model_id:
        raise ValueError(
            f"--model {args.model!r} does not match --embedding {args.embedding!r} "
            f"(expected {backend.model_id!r})."
        )
    args.embedding_pg_column = backend.pg_column

    try:
        if args.run_eval:
            return _run_eval(args)

        if not args.query:
            sys.stderr.write("Provide --query or enable --run-eval.\n")
            return 2
        return _run_single_query(args, args.query)
    except Exception as exc:
        if args.verbose:
            logging.exception("Retrieval failed.")
        sys.stderr.write(f"demo.py error: {exc}\n")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
