#!/usr/bin/env python3
"""
PA2 retrieval demo for course markers (Phase 5).

Purpose:
- Accept a natural-language query.
- Embed the query with the same embedding model used for segment indexing.
- Search `crawldb.page_segment` with pgvector similarity operators.
- Optionally rerank candidates with a cross-encoder.
- Provide a built-in qualitative evaluation mode (3 good + 3 weak queries).

System role:
- Depends on embeddings generated by `embed_page_segments.py`.
- Reads from `crawldb.page_segment` and joins source URL from `crawldb.page`.

Created: 2026-05-06
Major revisions:
- 2026-05-06: Implemented retrieval CLI, metric experiments, reranking, and eval mode.
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from dataclasses import dataclass
from typing import Any, Sequence

import psycopg
from pgvector.psycopg import register_vector

from embedding_common import MODEL_NAME, encode_texts, resolve_conn_kwargs

METRIC_TO_OPERATOR = {
    "cosine": "<=>",
    "l2": "<->",
    "inner_product": "<#>",
    "l1": "<+>",
}

EVAL_QUERY_SETS = {
    "good": [
        "How do I run DeepLabV3+ training with this repository?",
        "Which configuration keys control optimizer learning rate?",
        "How can I use a pretrained segmentation model from the README?",
    ],
    "weak": [
        "What is the best segmentation model for medical biology images in 2026?",
        "How does this project compare to Segment Anything 2 benchmarks?",
        "Can this codebase guarantee state-of-the-art mIoU on every dataset?",
    ],
}


@dataclass(frozen=True)
class RetrievalHit:
    """One retrieved segment with optional reranking metadata."""

    segment_id: int
    page_id: int
    chunk_index: int
    strategy: str
    distance: float
    segment_text: str
    source_url: str | None
    rerank_score: float | None = None


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Build CLI argument parser and return parsed namespace."""
    parser = argparse.ArgumentParser(
        description="PA2 demo: semantic retrieval over crawldb.page_segment embeddings."
    )
    parser.add_argument(
        "--query",
        type=str,
        default=None,
        help="Natural-language query to retrieve against segment embeddings.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Number of results to display (default: 5).",
    )
    parser.add_argument(
        "--strategy",
        type=str,
        default="heading_structure_v2",
        help="Optional segment strategy filter (default: heading_structure_v2).",
    )
    parser.add_argument(
        "--metric",
        choices=tuple(METRIC_TO_OPERATOR.keys()),
        default="cosine",
        help="Similarity metric/operator to use (default: cosine).",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=MODEL_NAME,
        help=(
            "SentenceTransformer model used for query embedding. Must be dimension-compatible "
            "with stored vectors."
        ),
    )
    parser.add_argument(
        "--rerank",
        action="store_true",
        help="Enable cross-encoder reranking over retrieved candidates.",
    )
    parser.add_argument(
        "--rerank-model",
        type=str,
        default="cross-encoder/ms-marco-MiniLM-L-6-v2",
        help="Cross-encoder model name used when --rerank is enabled.",
    )
    parser.add_argument(
        "--candidate-k",
        type=int,
        default=20,
        help="Candidate pool size before reranking (default: 20).",
    )
    parser.add_argument(
        "--database-url",
        type=str,
        default=os.environ.get("DATABASE_URL"),
        help="PostgreSQL connection URI. If omitted, falls back to PG* environment variables.",
    )
    parser.add_argument(
        "--run-eval",
        action="store_true",
        help="Run built-in qualitative query set (3 good + 3 weak queries).",
    )
    parser.add_argument(
        "--show-chars",
        type=int,
        default=260,
        help="Number of text characters to show per hit preview (default: 260).",
    )
    parser.add_argument(
        "--no-normalize",
        action="store_true",
        help="Disable L2 normalization when embedding the query.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable DEBUG logging.",
    )
    return parser.parse_args(argv)


def _connect(database_url: str | None) -> Any:
    """Create PostgreSQL connection and register pgvector adapter."""
    if database_url:
        conn = psycopg.connect(database_url, autocommit=True)
    else:
        conn = psycopg.connect(**resolve_conn_kwargs(), autocommit=True)
    conn.execute("SET search_path TO crawldb, public")
    register_vector(conn)
    return conn


def _embed_query(query: str, *, model_name: str, normalize_embeddings: bool) -> Any:
    """Encode one query text and return vector payload acceptable by pgvector."""
    embeddings = encode_texts(
        [query],
        normalize_embeddings=normalize_embeddings,
        model_name=model_name,
    )
    return embeddings[0]


def _retrieve_hits(
    conn: Any,
    *,
    query_vector: Any,
    top_k: int,
    strategy: str | None,
    metric: str,
) -> list[RetrievalHit]:
    """Execute metric-aware vector search and map rows to typed hits."""
    operator = METRIC_TO_OPERATOR[metric]
    sql = f"""
SELECT
    ps.id,
    ps.page_id,
    ps.chunk_index,
    ps.strategy,
    ps.segment_text,
    p.url,
    (ps.embedding {operator} %s) AS distance
FROM crawldb.page_segment ps
JOIN crawldb.page p ON p.id = ps.page_id
WHERE ps.embedding IS NOT NULL
"""
    params: list[Any] = [query_vector]
    if strategy:
        sql += " AND ps.strategy = %s"
        params.append(strategy)
    sql += " ORDER BY distance ASC LIMIT %s"
    params.append(top_k)

    rows = conn.execute(sql, params).fetchall()
    return [
        RetrievalHit(
            segment_id=int(row[0]),
            page_id=int(row[1]),
            chunk_index=int(row[2]),
            strategy=str(row[3]),
            segment_text=str(row[4] or ""),
            source_url=str(row[5]) if row[5] is not None else None,
            distance=float(row[6]),
        )
        for row in rows
    ]


def _rerank_hits(
    query: str,
    hits: Sequence[RetrievalHit],
    *,
    rerank_model: str,
    top_k: int,
) -> list[RetrievalHit]:
    """Rerank candidates with a cross-encoder and return top-ranked hits."""
    from sentence_transformers import CrossEncoder

    if not hits:
        return []
    model = CrossEncoder(rerank_model)
    pairs = [[query, hit.segment_text] for hit in hits]
    scores = model.predict(pairs)

    scored = [
        RetrievalHit(
            segment_id=hit.segment_id,
            page_id=hit.page_id,
            chunk_index=hit.chunk_index,
            strategy=hit.strategy,
            distance=hit.distance,
            segment_text=hit.segment_text,
            source_url=hit.source_url,
            rerank_score=float(score),
        )
        for hit, score in zip(hits, scores, strict=True)
    ]
    scored.sort(key=lambda item: item.rerank_score if item.rerank_score is not None else -1e9, reverse=True)
    return scored[:top_k]


def _format_preview(text: str, *, max_chars: int) -> str:
    """Render one-line preview for stable terminal output."""
    compact = " ".join(text.strip().split())
    if len(compact) <= max_chars:
        return compact
    return compact[: max_chars - 3] + "..."


def _print_hits(
    hits: Sequence[RetrievalHit],
    *,
    metric: str,
    show_chars: int,
    reranked: bool,
) -> None:
    """Print retrieval results in marker-friendly format."""
    if not hits:
        print("No hits found for this query.")
        return

    for rank, hit in enumerate(hits, start=1):
        preview = _format_preview(hit.segment_text, max_chars=show_chars)
        score_label = "rerank_score" if reranked else "distance"
        score_value = hit.rerank_score if reranked else hit.distance
        print(f"[{rank}] {score_label}={score_value:.6f} metric={metric}")
        print(
            f"    page_id={hit.page_id} segment_id={hit.segment_id} "
            f"chunk_index={hit.chunk_index} strategy={hit.strategy}"
        )
        print(f"    url={hit.source_url or 'N/A'}")
        print(f"    text={preview}")


def _run_single_query(args: argparse.Namespace, query: str) -> int:
    """Execute one retrieval request and print results."""
    if args.metric != "cosine":
        logging.warning(
            "Metric '%s' has no matching ANN index in current migration (cosine HNSW only). "
            "Query is still valid, but may run slower.",
            args.metric,
        )

    query_vector = _embed_query(
        query,
        model_name=args.model,
        normalize_embeddings=not args.no_normalize,
    )
    candidate_k = max(args.top_k, args.candidate_k if args.rerank else args.top_k)

    with _connect(args.database_url) as conn:
        initial_hits = _retrieve_hits(
            conn,
            query_vector=query_vector,
            top_k=candidate_k,
            strategy=args.strategy,
            metric=args.metric,
        )

    final_hits = initial_hits[: args.top_k]
    reranked = False
    if args.rerank:
        try:
            final_hits = _rerank_hits(
                query,
                initial_hits,
                rerank_model=args.rerank_model,
                top_k=args.top_k,
            )
            reranked = True
        except Exception as exc:
            logging.warning("Reranking failed, falling back to base retrieval: %s", exc)

    print(f"\nQuery: {query}")
    print(
        "Mode: "
        f"metric={args.metric} top_k={args.top_k} strategy={args.strategy or 'ALL'} "
        f"rerank={'on' if reranked else 'off'}"
    )
    _print_hits(
        final_hits,
        metric=args.metric,
        show_chars=args.show_chars,
        reranked=reranked,
    )
    return 0


def _run_eval(args: argparse.Namespace) -> int:
    """Run built-in qualitative query set required by the assignment."""
    print("Running qualitative evaluation set (3 good + 3 weak queries).")
    for bucket in ("good", "weak"):
        print(f"\n=== {bucket.upper()} QUERIES ===")
        for index, query in enumerate(EVAL_QUERY_SETS[bucket], start=1):
            print(f"\n--- {bucket} #{index} ---")
            _run_single_query(args, query)
    return 0


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(message)s",
    )

    if args.top_k <= 0:
        raise ValueError("--top-k must be > 0")
    if args.candidate_k <= 0:
        raise ValueError("--candidate-k must be > 0")
    if args.show_chars <= 0:
        raise ValueError("--show-chars must be > 0")

    try:
        if args.run_eval:
            return _run_eval(args)

        if not args.query:
            sys.stderr.write("Provide --query or enable --run-eval.\n")
            return 2
        return _run_single_query(args, args.query)
    except Exception as exc:
        if args.verbose:
            logging.exception("Retrieval failed.")
        sys.stderr.write(f"demo.py error: {exc}\n")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
